name: Run Makefile with Python and R

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'  # Specify the R version you need

    - name: Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('tidyverse','hrbrthemes'), dependencies = TRUE, repos='https://cloud.r-project.org')"

    - name: Install Remotes
      run: |
        Rscript -e "install.packages('remotes', dependencies = TRUE, repos='https://cloud.r-project.org')"

    - name: Install CDCFluView
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
      run: |
        Rscript -e "remotes::install_github('hrbrmstr/cdcfluview')"

    # Set up Python environment
    - name: Set up Python
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Run the Makefile
    - name: Run Makefile
      run: |
        source .venv/bin/activate
        make

    # Commit and push both CSV files
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        add: |
          clinical_and_public_lab_data__formatted.csv
          ilidata.csv
          ili_plus.csv
        message: "Add generated clinical_and_public_lab_data__formatted.csv and ilidata.csv from Makefile run"
        default_author: github_actions
        push: true
