name: Run Makefile with Python and R

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'  # Specify the R version you need

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('tidyverse','hrbrthemes','cdcfluview'), repos='https://cloud.r-project.org')"

    # Run the Makefile
    - name: Run Makefile
      run: |
        source .venv/bin/activate
        make
